[package]
name = "calyptra"
edition.workspace = true
version.workspace = true

[dependencies]
anim = { path = "../anim" }
render = { path = "../render" }
eframe.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
wgpu.workspace = true
log.workspace = true
env_logger.workspace = true
anyhow.workspace = true
glam.workspace = true
scene = { path = "../scene" }
color = { path = "../color" }
formulas = { path = "../formulas" }
export = { path = "../export" }
rfd = "0.17"

[build-dependencies]
embed-resource = "3"
