[package]
name = "render"
edition.workspace = true
version.workspace = true

[dependencies]
wgpu.workspace = true
bytemuck.workspace = true
log.workspace = true
glam.workspace = true
scene = { path = "../scene" }
color = { path = "../color" }
formulas = { path = "../formulas" }

[dev-dependencies]
formulas = { path = "../formulas" }
pollster = "1"
png = "0.18"
