//! Formula library and shader composer.
//!
//! A formula is a WGSL file defining one iteration step. A metadata header of
//! `// @key value` lines describes it:
//!
//! ```text
//! // @name Mandelbox            display name
//! // @de linear                 logarithmic | linear | box
//! // @bailout 100               suggested escape radius
//! // @param scale -1.5 -3 3     name default min max (repeatable, max 8)
//! fn mandelbox(z: ptr<function, vec3<f32>>, dr: ptr<function, f32>,
//!              c: vec3<f32>, P: mandelbox_Params) { ... }
//! ```
//!
//! The function is named after the file stem (the formula id). It updates
//! `z` and the running derivative `dr`; `c` is the constant to add (the
//! sample position, or the Julia constant). `<id>_Params` is generated by
//! the composer with one `f32` field per `@param`. Helper functions must be
//! prefixed with the id to avoid clashes in hybrids.

mod compose;
mod library;
mod presets;

pub use compose::{ComposeError, compose};
pub use library::{FormulaDef, Library, ParamDef, parse_formula};
pub use presets::{Preset, presets};
